<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <OptimizationPreference Condition="'$(RinhaOptimizationPreference)' != ''">$(RinhaOptimizationPreference)</OptimizationPreference>
    <IlcInstructionSet Condition="'$(RinhaIlcInstructionSet)' != ''">$(RinhaIlcInstructionSet)</IlcInstructionSet>
    <IlcMaxVectorTBitWidth Condition="'$(RinhaIlcMaxVectorTBitWidth)' != ''">$(RinhaIlcMaxVectorTBitWidth)</IlcMaxVectorTBitWidth>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
