FROM alpine:3.22 AS build
WORKDIR /src

ARG ILC_INSTRUCTION_SET=avx2,bmi2,fma,pclmul,popcnt,aes
ARG ILC_MAX_VECTOR_T_BIT_WIDTH=256

RUN apk add --no-cache bash curl ca-certificates clang lld build-base zlib-dev icu-libs

RUN curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh \
    && bash /tmp/dotnet-install.sh --version 10.0.203 --install-dir /root/.dotnet

ENV PATH="/root/.dotnet:${PATH}"

COPY . .

RUN dotnet publish src/Rinha2026.Api/Rinha2026.Api.csproj \
    -c Release \
    -r linux-musl-x64 \
    -o /out/api \
    --self-contained true \
    -p:OptimizationPreference=Speed \
    -p:PublishAot=true \
    -p:IlcInstructionSet=${ILC_INSTRUCTION_SET} \
    -p:IlcMaxVectorTBitWidth=${ILC_MAX_VECTOR_T_BIT_WIDTH} \
    -p:StaticExecutable=true \
    -p:StripSymbols=true

FROM scratch AS runtime
WORKDIR /app

LABEL org.opencontainers.image.source="https://github.com/Hanake0/rinha-backend-2026-csharp-nativeaot"
LABEL org.opencontainers.image.description="Rinha de Backend 2026 C# NativeAOT API submission image"

ENV ASPNETCORE_URLS=http://+:9999
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY --from=build /out/api ./
COPY submission-data/ /app/data/

EXPOSE 9999

ENTRYPOINT ["./Rinha2026.Api"]
