FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

RUN apt-get update \
    && apt-get install -y --no-install-recommends clang zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN dotnet publish src/Rinha2026.Api/Rinha2026.Api.csproj \
    -c Release \
    -r linux-x64 \
    -o /out/api \
    --self-contained true \
    -p:PublishAot=true \
    -p:StripSymbols=true

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-noble AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:9999
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY --from=build /out/api ./

EXPOSE 9999

ENTRYPOINT ["./Rinha2026.Api"]
