FROM alpine:3.22 AS build
WORKDIR /src

ARG ILC_INSTRUCTION_SET=x86-64-v3,aes
ARG ILC_MAX_VECTOR_T_BIT_WIDTH=256
ARG OPTIMIZATION_PREFERENCE=Speed

RUN apk add --no-cache bash curl ca-certificates clang lld build-base zlib-dev icu-libs

RUN curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh \
    && bash /tmp/dotnet-install.sh --version 10.0.203 --install-dir /root/.dotnet

ENV PATH="/root/.dotnet:${PATH}"
ENV RinhaOptimizationPreference=${OPTIMIZATION_PREFERENCE}
ENV RinhaIlcInstructionSet=${ILC_INSTRUCTION_SET}
ENV RinhaIlcMaxVectorTBitWidth=${ILC_MAX_VECTOR_T_BIT_WIDTH}

COPY . .

RUN dotnet publish src/Rinha2026.Api/Rinha2026.Api.csproj \
    -c Release \
    -r linux-musl-x64 \
    -o /out/api \
    --self-contained true \
    -p:PublishAot=true \
    -p:StaticExecutable=true \
    -p:StripSymbols=true

FROM scratch AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:9999
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY --from=build /out/api ./

EXPOSE 9999

ENTRYPOINT ["./Rinha2026.Api"]
