services:
  api1:
    environment:
      Runtime__Diagnostics__ProfileEnabled: "true"
      Runtime__Diagnostics__ProfileSamplingStride: "64"
    ports:
      - "10001:9999"

  api2:
    environment:
      Runtime__Diagnostics__ProfileEnabled: "true"
      Runtime__Diagnostics__ProfileSamplingStride: "64"
    ports:
      - "10002:9999"
